In [1]:
import numpy as np

In [3]:
b = np.array([1, 2, 3, 4, 5], dtype=float)

In [4]:
b = np.array([1, 2, 3, 4, 5], dtype=float)

In [5]:
b = np.array(1, 2, 3, 4, 5, dtype=float)

ValueError: only 2 non-keyword arguments accepted

In [7]:
c = np.array([False, False, True])

In [8]:
f = np.arange(1, 2, 0.3, dtype=float)

In [9]:
f

array([1. , 1.3, 1.6, 1.9])

In [10]:
c

array([False, False,  True])

In [11]:
b

array([1., 2., 3., 4., 5.])

In [13]:
a = np.array([0, -1, 11])
b = np.array([3, 7, 2])

In [16]:
r1 = b.dot(a)
r2 = np.dot(a, b) / np.linalg.norm(a) / np.linalg.norm(b)
r3 = a * b
r4 = np.dot(a, b)

r1

In [17]:
r1

15

In [18]:
r2

0.1724707686818527

In [19]:
r3

array([ 0, -7, 22])

In [20]:
r4

15

In [21]:
a = np.array([6, 3, -5])

In [22]:
a = a.reshape((1, 3))

In [23]:
ф

SyntaxError: invalid syntax (<ipython-input-23-f83b14a9c292>, line 1)

In [24]:
a

array([[ 6,  3, -5]])

In [25]:
a = a.reshape((3, 1))

In [26]:
a

array([[ 6],
       [ 3],
       [-5]])

In [29]:
d = np.ones((10, 10))


e = np.arange(1, 13, 2).reshape((3, 2))


b = np.eye(2, 3)


In [30]:
d

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [31]:
e

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

In [32]:
b

array([[1., 0., 0.],
       [0., 1., 0.]])

In [33]:
a = np.eye(4, 5)

In [34]:
 a[[0, 3], [1, 3]]

array([0., 1.])